### PR TITLE
@Chipped Glowstone + Planks are missing stonecutter recipes.

### LINKED ISSUE #3673: @Chipped Glowstone + Planks are missing stonecutter recipes.
### Modpack Version

Enigmatica 6 - 0.5.20+ (commit f9d402d6bb206f1d077530e639b77b6ddc604b65 in dev branch)

### Describe your issue.

@Chipped's glowstone and planks are missing stonecutter recipes. This seems to be my pet issue, so here's more decorative blocks that are missing their stonecutter recipes.

Attempt at a pull request coming in a few minutes, as soon as I double check it's not broken.

### Crash Report

N/A

### Latest Log

N/A

### Have you modified the modpack?

Yes

### User Modifications

Removed roadrunner, disabled mosquito spawns 

### Did the issue happen in singleplayer or on a server?

Singleplayer

### PR DESCRIPTION
**Pull request by Iris-xii**
Fixes #3673 

This might not be the right approach, or it might be broken! Though I've double-checked, it wouldn't be the first time something slips by.

It adds a stonecutter recipe for Chipped's glowstone by adding the forge:storage_blocks/glowstone tag to it.
It adds the planks to stonecuttables.js.

### CODE REVIEW

File: kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js [hunk 1]
```diff
@@ -2455,13 +2457,19 @@ chiselPlankVariants = [
     'braid',
     'log_cabin'
 ];
-chiselPlankTypes.forEach((chiselPlankType) => {
-    let stones = [`minecraft:${chiselPlankType}_planks`];
-    chiselPlankVariants.forEach((chiselPlankVariant) => {
-        stones.push(`chisel:planks/${chiselPlankType}/${chiselPlankVariant}`);
-    });
+plankTypes.forEach((plankType) => {
+	const numberChippedVariants = 18;
```
Comment (NillerMedDild) [inline kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js:2461]: Please put this outside the loop :)

File: kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage_blocks.js [hunk 2]
```diff
@@ -59,4 +59,5 @@ onEvent('item.tags', (event) => {
     event.add(storageBlocks + '/glowstone', ['#chisel:glowstone']);
     event.add(storageBlocks + '/redstone', ['#chisel:redstone']);
     event.add(storageBlocks + '/coal', ['#chisel:coal']);
+	event.add(storageBlocks + '/glowstone', ['#chipped:glowstone']);
```
Comment (NillerMedDild) [inline kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage_blocks.js:62]: I recommend adding the Prettier extension to Visual Studio Code (if you're using that) to autoformat on save, so avoid indentation errors like this :)

**Review by NillerMedDild — CHANGES_REQUESTED** [review]

**Comment by NillerMedDild** [comment]
Looks like the right approach to me, just that one change and it's good to go, thank you :D

File: kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage_blocks.js (hunk 2 above)
Comment (Iris-xii) [reply kubejs/server_scripts/enigmatica/kubejs/base/tags/items/forge/storage_blocks.js]: I'm using Notepad++, I'll try to watch out and not spew janky identation all over next time though - or switch to something else if this becomes too much of a regular thing!

File: kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js (hunk 1 above)
Comment (Iris-xii) [reply kubejs/server_scripts/enigmatica/kubejs/constants/stonecuttables.js]: Oops yeah that probably shouldn't go there

**Comment by Iris-xii** [comment]
There, I think that should be it unless there are any other changes you'd like me to make. Thank you for your patience!

**Review by NillerMedDild — APPROVED** [review]

**Comment by NillerMedDild** [comment]
Perfect, thank you :)
